CREATE DATABASE SISTRANLATAM
USE SISTRANLATAM;

CREATE TABLE CLIENTES
(
	IDCLIENTE INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(100),
	APELLIDO VARCHAR(100),
	IDTIPODOCUMENTO INT,
	NUMERODOCUMENTO VARCHAR(250),
	FECHANACIMIENTO DATE,
	TELEFONO1 VARCHAR(50),
	TELEFONO2 VARCHAR(50),
	CORREO1 VARCHAR(250),
	CORREO2 VARCHAR(250),
	IDCIUDAD INT,
	DIRECCION1 VARCHAR(50),
	DIRECCION2 VARCHAR(50)
)


CREATE TABLE TIPODOCUMENTO
(
	IDTIPODOCUMENTO INT NOT NULL,
	TIPODOCUMENTO VARCHAR(50)
)


CREATE TABLE CIUDAD
(
	IDCIUDAD INT NOT NULL,
	NOMBRECIUDAD VARCHAR(50)
)
