IF EXISTS (SELECT 1 WHERE OBJECT_ID('SSP_INSCLIENTES') > 0)
			BEGIN
				DROP PROCEDURE SSP_INSCLIENTES
			END
			GO
	CREATE PROCEDURE SSP_INSCLIENTES
	(
		@INNOMBRE VARCHAR(50),
		@INAPELLIDO VARCHAR(50),
		@INTIPODOCUMENTO INT,
		@INNUMERODOCUMENTO VARCHAR(50),
		@INFECHANACIMIENTO DATE,
		@INTELEFONO1 VARCHAR(50),
		@INTELEFONO2 VARCHAR(50),
		@INCORREO1 VARCHAR(50),
		@INCORREO2 VARCHAR(50),
		@INCIUDAD INT,
		@INDIRECCION1 VARCHAR(50),
		@INDIRECCION2 VARCHAR(50),
		@MENSAJE VARCHAR(200) output,
		@ULTIMO INT OUTPUT
	)
	AS 
		SET NOCOUNT ON
		BEGIN TRY      
			IF NOT EXISTS ( SELECT NUMERODOCUMENTO FROM CLIENTES WHERE NUMERODOCUMENTO = @INNUMERODOCUMENTO) 
				BEGIN    
					INSERT INTO CLIENTES(NOMBRE, APELLIDO, IDTIPODOCUMENTO, NUMERODOCUMENTO, FECHANACIMIENTO, TELEFONO1,TELEFONO2, CORREO1,CORREO2, IDCIUDAD, DIRECCION1,DIRECCION2 )
					VALUES ( @INNOMBRE, @INAPELLIDO,@INTIPODOCUMENTO,@INNUMERODOCUMENTO,@INFECHANACIMIENTO,@INTELEFONO1,@INTELEFONO2,@INCORREO1,@INCORREO2,@INCIUDAD,@INDIRECCION1,@INDIRECCION2)
					SET @ULTIMO = SCOPE_IDENTITY()    
					SET @MENSAJE = 'Guardado...'        
				END    
			ELSE 
				BEGIN    
					SET @ULTIMO = 0    
					SET @MENSAJE = 'El cliente que intenta registrar ya existe!'        
				END    
		END TRY      
		BEGIN CATCH      
			set @MENSAJE = SUBSTRING(( SELECT ERROR_MESSAGE()), 1, 200)      
		END CATCH
		SELECT * FROM CLIENTES