IF EXISTS (SELECT 1 WHERE OBJECT_ID('SSP_SETCLIENTES') > 0)
			BEGIN
				DROP PROCEDURE SSP_SETCLIENTES
			END
			GO
	CREATE PROCEDURE SSP_SETCLIENTES
	(
		@INIDCLIENTE INT,
		@INNOMBRE VARCHAR(50),
		@INAPELLIDO VARCHAR(50),
		@INTELEFONO1 VARCHAR(50),
		@INTELEFONO2 VARCHAR(50),
		@INCORREO1 VARCHAR(50),
		@INCORREO2 VARCHAR(50),
		@INCIUDAD INT,
		@INDIRECCION1 VARCHAR(50),
		@INDIRECCION2 VARCHAR(50),
		@MENSAJE VARCHAR(200) output
	)
	AS 
		SET NOCOUNT ON
		BEGIN TRY      
			IF EXISTS ( SELECT TOP 1 1 FROM CLIENTES WHERE IDCLIENTE = @INIDCLIENTE) 
				BEGIN    
					UPDATE CLIENTES SET NOMBRE = @INNOMBRE,APELLIDO = @INAPELLIDO, TELEFONO1 = @INTELEFONO1,TELEFONO2 = @INTELEFONO2,CORREO1 = @INCORREO1,
					CORREO2 = @INCORREO2,IDCIUDAD = @INCIUDAD,DIRECCION1 = @INDIRECCION1,DIRECCION2 = @INDIRECCION2 WHERE IDCLIENTE = @INIDCLIENTE
					SET @MENSAJE = 'Actualizado...'        
				END    
			ELSE 
				BEGIN        
					SET @MENSAJE = 'El cliente que intenta actualizar no esta registrado'        
				END    
		END TRY      
		BEGIN CATCH      
			set @MENSAJE = SUBSTRING(( SELECT ERROR_MESSAGE()), 1, 200)      
		END CATCH
		SELECT * FROM CLIENTES

	