IF EXISTS (SELECT 1 WHERE OBJECT_ID('SSP_DELCLIENTES') > 0)
			BEGIN
				DROP PROCEDURE SSP_DELCLIENTES
			END
			GO
	CREATE PROCEDURE SSP_DELCLIENTES
	(
		@INIDCLIENTES INT,
		@MENSAJE varchar(200) OUTPUT
	)
	AS 
		SET NOCOUNT ON
		BEGIN TRY  	
			IF EXISTS (SELECT TOP 1 1 FROM CLIENTES WHERE IDCLIENTE = @INIDCLIENTES)
				BEGIN 
					DELETE CLIENTES
					WHERE IDCLIENTE = @INIDCLIENTES 
					SET @MENSAJE = 'Borrado...'
				END  
			ELSE
				BEGIN
					SET @MENSAJE = 'No existe el cliente seleccionado' 
				END   
		END TRY      
		BEGIN CATCH      
			SET @MENSAJE = SUBSTRING(( SELECT ERROR_MESSAGE()), 1, 200)      
		END CATCH