IF EXISTS (SELECT 1 WHERE OBJECT_ID('SSP_GETCLIENTES') > 0)
		BEGIN
			DROP PROCEDURE SSP_GETCLIENTES
		END
		GO 

		CREATE PROCEDURE SSP_GETCLIENTES
			AS
			SET NOCOUNT ON
			SELECT C.IDCLIENTE, C.NOMBRE , C.APELLIDO, TD.IDTIPODOCUMENTO ,C.NUMERODOCUMENTO, C.FECHANACIMIENTO,
			C.TELEFONO1, C.TELEFONO2, C.CORREO1, C.CORREO2,CI.NOMBRECIUDAD, C.DIRECCION1, C.DIRECCION2
			FROM CLIENTES AS C
			JOIN TIPODOCUMENTO AS TD
			ON TD.IDTIPODOCUMENTO = C.IDTIPODOCUMENTO
			JOIN CIUDAD AS CI
			ON CI.IDCIUDAD = C.IDCIUDAD